common_args:
  training_type: "simulation"
  random_seed: 3
  config_version: release

data_args:
  dataset: "synthetic_1_1"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5
  stragglers_percent: 10
  data_compute_correlation: 0.5

model_args:
  model: "lr"

train_args:
  federated_optimizer: "FedCore"
  client_id_list: "[]"
  client_num_in_total: 30
  client_num_per_round: 10
  comm_round: 100
  epochs: 10
  batch_size: 8
  client_optimizer: sgd
  learning_rate: 0.01
  weight_decay: 0.001
  fedprox_mu: 0

validation_args:
  frequency_of_the_test: 1

device_args:
  using_gpu: false
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
  # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_tracking: false
  enable_wandb: false
  log_file_dir: ./log
  mlops_api_key: 0433f1a15fc54ba3bedd389e41524f73
  mlops_project_name: simulation
  mlops_run_name: fedml_torch_fedcore_mnist_lr
  record_dir: ./log
  record_file: fedcore_syn11_lr
